networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: "11.1.0.0/24"

services:
  postgres:
    networks:
      network:
        ipv4_address: 11.1.0.100
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./create_test_db.sh:/docker-entrypoint-initdb.d/create_test_db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d admin_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    networks:
      network:
        ipv4_address: 11.1.0.11
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy

  tests:
    networks:
      network:
        ipv4_address: 11.1.0.12
    build: .
    env_file:
      - .env
    container_name: tests
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["pytest", "--tb=short", "--disable-pytest-warnings"]

volumes:
  postgres: